version: '3.8'

services:
  aerostack2:
    container_name: aerostack_lead_2
    image: aerostack2_custom:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    network_mode: host
    ipc: host
    pid: host
    entrypoint: ["/bin/bash", "-c", "sleep infinity"]
    environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - GZ_SIM_RESOURCE_PATH=/home/developer/aerostack2_ws/src/sim_environment/models
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./aerostack2_ws/src:/home/developer/aerostack2_ws/src
    user: developer
    stdin_open: true
    tty: true